### ISSUE TITLE
Game didnt start when Piercing Paxels is Installed

### ISSUE THREAD

**Issue by Briatkee** [AmyMialeeMods/piercingpaxels#24] opened 2023-06-15 10:48 UTC
When i start my game it crash with exit code -1 and no crash-report where created 

Envoirement
Minecraft Fabric 1.20 Latest

Latest.log
https://pastebin.com/Efxn3ik9

**Comment by AmyMialee** [comment] 2023-06-15 11:21
duplicate of #21

**Closed** 2023-06-15 11:21 UTC
